services:
  electra-sems:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
    volumes:
      - ./examples:/app/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
